/**
 * @casinogames/engine — the platform-agnostic core of the demo.
 *
 * Everything that decides an outcome or moves money lives here: RNG, dice,
 * shoe, round state machines, settlement and math. The package has zero
 * runtime dependencies and compiles against the bare ES2022 library (no DOM,
 * no Node typings), so the same code can run in a browser or on a server.
 */
export {
  ACE,
  JACK,
  KING,
  QUEEN,
  RANK_SETS,
  SUITS,
  cardCode,
  cardLabel,
  isRank,
  isRed,
  parseCardCode,
  rankLabel,
  rankRange,
  suitSymbol,
  type Card,
  type Rank,
  type Suit,
} from './cards/card.ts';
export {
  DEFAULT_PENETRATION,
  Shoe,
  ShoeExhaustedError,
  type CardSource,
  type ShoeOptions,
} from './cards/shoe.ts';
export {
  DIE_FACES,
  diceTotal,
  isDieFace,
  rollDice,
  rollDie,
  type DicePair,
  type DieFace,
} from './dice/dice.ts';
export { EngineError, type EngineErrorCode } from './game/errors.ts';
export { expectedMeterAtHit, progressiveRtpAtMeter, summarizeMath } from './game/math-summary.ts';
export {
  isCents,
  odds,
  oddsLabel,
  oddsMultiplier,
  winnings,
  type Cents,
  type Odds,
} from './game/money.ts';
export {
  RoundBuilder,
  continueRound,
  startRound,
  type EmittableEvent,
  type GameInfo,
} from './game/round.ts';
export {
  settleLoss,
  settlePush,
  settleWin,
  settleWithPayout,
  settlementTotals,
  withFee,
  type Outcome,
  type Settlement,
  type SettlementLine,
  type SettlementTotals,
} from './game/settlement.ts';
export type {
  BetBreakdown,
  BetDefinition,
  BetId,
  BetKind,
  BetMath,
  Bets,
  BreakdownRow,
  CustomEvent,
  DecisionOption,
  DecisionSummary,
  FiniteShoeFigures,
  Game,
  GameEvent,
  GameEventType,
  JackpotPayout,
  MathSummary,
  PaytableCondition,
  PaytableEntry,
  ProgressiveMath,
  ProgressiveTerms,
  RoundPhase,
  RoundState,
  StrategyCard,
  StrategyFigures,
  StrategyRow,
} from './game/types.ts';
export { defineBets, validateBets } from './game/validation.ts';
export { playRound, type Strategy } from './game/play.ts';
export {
  enumerateOutcomes,
  type EnumerateOptions,
  type WeightedOutcome,
} from './math/enumerate.ts';
export { exactReturns, type ExactReport, type ExactReturn } from './math/exact.ts';
export { Fraction } from './math/fraction.ts';
export { GAMES } from './games/index.ts';
export {
  EXACT_HIT_ODDS,
  MOVING_TARGET_BETS,
  MOVING_TARGET_BET_IDS,
  MOVING_TARGET_DEALER,
  MOVING_TARGET_ID,
  MOVING_TARGET_NAME,
  MAX_CARD_VALUE,
  FIRST_CARD_ODDS,
  TARGETS,
  THREE_PLUS_MIN_CARDS,
  THREE_PLUS_CARDS_ODDS,
  movingTargetMathSummary,
  movingTargetOutlook,
  cardValue,
  createMovingTarget,
  createMovingTargetShoe,
  readMovingTargetDeal,
  resolveMovingTargetBet,
  targetOf,
  type MovingTargetBetId,
  type MovingTargetDeal,
  type MovingTargetGame,
  type MovingTargetOptions,
  type MovingTargetOutlook,
  type MovingTargetResolution,
  type Target,
} from './games/moving-target/index.ts';
export {
  DOUBLES_ODDS,
  DICE_SPREAD_BETS,
  DICE_SPREAD_BET_IDS,
  DICE_SPREAD_DEALER,
  DICE_SPREAD_ID,
  DICE_SPREAD_NAME,
  BETWEEN_ODDS,
  MATCH_ODDS,
  BULLSEYE_ODDS,
  TRIPLE_ODDS,
  createDiceSpread,
  createDiceSpreadShoe,
  diceSpreadMathSummary,
  readDiceSpreadRoll,
  resolveDiceSpreadBet,
  type DiceSpreadBetId,
  type DiceSpreadGame,
  type DiceSpreadOptions,
  type DiceSpreadResolution,
  type DiceSpreadRoll,
  type Spread,
} from './games/dice-spread/index.ts';
export {
  MIRROR_BETS,
  MIRROR_BET_IDS,
  MIRROR_CONFIG,
  MIRROR_DEALER,
  MIRROR_ID,
  MIRROR_MATH,
  MIRROR_NAME,
  JACKPOT_BET,
  DOUBLE_SIXES_FIXED_RTP,
  DOUBLE_SIXES_RTP,
  DOUBLE_SIXES_RTP_AT_SEED,
  compareHands,
  createMirror,
  createMirrorJackpot,
  createMirrorShoe,
  mirrorMathSummary,
  mirrorOutlook,
  readHand,
  resolveMirrorBet,
  type MirrorBetId,
  type MirrorGame,
  type MirrorHand,
  type MirrorOptions,
  type MirrorOutlook,
  type MirrorResolution,
  type HandValues,
  type JackpotMeterEvent,
} from './games/mirror/index.ts';
export {
  DISTINCT_ROLLS,
  INFINITE_SHOE,
  LOCK_AND_ROLL_BET,
  LOCK_AND_ROLL_BETS,
  LOCK_AND_ROLL_CONFIG,
  LOCK_AND_ROLL_DEALER,
  LOCK_AND_ROLL_DECISIONS,
  LOCK_AND_ROLL_ID,
  LOCK_AND_ROLL_MATH,
  LOCK_AND_ROLL_NAME,
  LOCK_AND_ROLL_SIX_DECK,
  LOCK_AND_ROLL_WITHOUT_FREE,
  WITHOUT_FREE_ONE_ONE,
  beatChance,
  bestChoice,
  createLockAndRoll,
  createLockAndRollShoe,
  feeRate,
  isFreeReroll,
  lockChoice,
  lockedDie,
  otherDie,
  paidLockFee,
  referenceStrategy,
  lockFee,
  rerollValue,
  rollLabel,
  rollValues,
  shoeTotals,
  standValue,
  strategyMath,
  lockAndRollMathSummary,
  lockAndRollOptions,
  lockAndRollStrategy,
  lockAndRollWins,
  withDie,
  type DealerTotals,
  type DieIndex,
  type DieRerolledEvent,
  type DistinctRoll,
  type RollStrategy,
  type RollValues,
  type StrategyMath,
  type LockAndRollBetId,
  type LockAndRollChoice,
  type LockAndRollData,
  type LockAndRollGame,
  type LockAndRollOptions,
  type LockAndRollRules,
  type LockAndRollState,
} from './games/lock-and-roll/index.ts';
export {
  roundsForTolerance,
  simulate,
  type BetStatistics,
  type SimulationOptions,
  type SimulationReport,
} from './math/simulate.ts';
export {
  ProgressiveJackpot,
  type ExactAmount,
  type ProgressiveOptions,
  type ProgressiveSnapshot,
  type ProgressiveState,
} from './progressive/progressive.ts';
export { createCryptoRng, type RandomValuesSource } from './rng/crypto.ts';
export { randomInt, shuffleInPlace, type IntegerRng, type Rng } from './rng/rng.ts';
export { createSeededRng, type Seed } from './rng/seeded.ts';
