/**
 * @casinogames/engine — the platform-agnostic core of the demo.
 *
 * Everything that decides an outcome or moves money lives here: RNG, dice,
 * shoe, round state machines, settlement and math. The package has zero
 * runtime dependencies and compiles against the bare ES2022 library (no DOM,
 * no Node typings), so the same code can run in a browser or on a server.
 */
export {
  ACE,
  JACK,
  KING,
  QUEEN,
  RANK_SETS,
  SUITS,
  cardCode,
  cardLabel,
  isRank,
  isRed,
  parseCardCode,
  rankLabel,
  rankRange,
  suitSymbol,
  type Card,
  type Rank,
  type Suit,
} from './cards/card.ts';
export {
  DEFAULT_PENETRATION,
  Shoe,
  ShoeExhaustedError,
  type CardSource,
  type ShoeOptions,
} from './cards/shoe.ts';
export {
  DIE_FACES,
  diceTotal,
  isDieFace,
  rollDice,
  rollDie,
  type DicePair,
  type DieFace,
} from './dice/dice.ts';
export { EngineError, type EngineErrorCode } from './game/errors.ts';
export { expectedMeterAtHit, progressiveRtpAtMeter, summarizeMath } from './game/math-summary.ts';
export {
  isCents,
  odds,
  oddsLabel,
  oddsMultiplier,
  winnings,
  type Cents,
  type Odds,
} from './game/money.ts';
export {
  RoundBuilder,
  continueRound,
  startRound,
  type EmittableEvent,
  type GameInfo,
} from './game/round.ts';
export {
  settleLoss,
  settlePush,
  settleWin,
  settleWithPayout,
  settlementTotals,
  withFee,
  type Outcome,
  type Settlement,
  type SettlementLine,
  type SettlementTotals,
} from './game/settlement.ts';
export type {
  BetBreakdown,
  BetDefinition,
  BetId,
  BetKind,
  BetMath,
  Bets,
  BreakdownRow,
  CustomEvent,
  DecisionOption,
  DecisionSummary,
  FiniteShoeFigures,
  Game,
  GameEvent,
  GameEventType,
  JackpotPayout,
  MathSummary,
  PaytableCondition,
  PaytableEntry,
  ProgressiveMath,
  ProgressiveTerms,
  RoundPhase,
  RoundState,
  StrategyCard,
  StrategyFigures,
  StrategyRow,
} from './game/types.ts';
export { defineBets, validateBets } from './game/validation.ts';
export { playRound, type Strategy } from './game/play.ts';
export {
  enumerateOutcomes,
  type EnumerateOptions,
  type WeightedOutcome,
} from './math/enumerate.ts';
export { exactReturns, type ExactReport, type ExactReturn } from './math/exact.ts';
export { Fraction } from './math/fraction.ts';
export { MATH_END, MATH_START, renderMathSection, replaceMathSection } from './math/sheet.ts';
export { GAMES } from './games/index.ts';
export {
  ACERTA_ODDS,
  ALVO_MOVEL_BETS,
  ALVO_MOVEL_BET_IDS,
  ALVO_MOVEL_DEALER,
  ALVO_MOVEL_ID,
  ALVO_MOVEL_NAME,
  MAX_CARD_VALUE,
  PRIMEIRA_CARTA_ODDS,
  TARGETS,
  TRES_OU_MAIS_CARDS,
  TRES_OU_MAIS_ODDS,
  alvoMovelMathSummary,
  alvoMovelOutlook,
  cardValue,
  createAlvoMovel,
  createAlvoMovelShoe,
  readAlvoMovelDeal,
  resolveAlvoMovelBet,
  targetOf,
  type AlvoMovelBetId,
  type AlvoMovelDeal,
  type AlvoMovelGame,
  type AlvoMovelOptions,
  type AlvoMovelOutlook,
  type AlvoMovelResolution,
  type Target,
} from './games/alvo-movel/index.ts';
export {
  DOBROS_ODDS,
  ENTRE_DADOS_BETS,
  ENTRE_DADOS_BET_IDS,
  ENTRE_DADOS_DEALER,
  ENTRE_DADOS_ID,
  ENTRE_DADOS_NAME,
  ENTRE_ODDS,
  EXATO_ODDS,
  OLHO_DE_BOI_ODDS,
  TRIPLO_ODDS,
  createEntreDados,
  createEntreDadosShoe,
  entreDadosMathSummary,
  readEntreDadosRoll,
  resolveEntreDadosBet,
  type EntreDadosBetId,
  type EntreDadosGame,
  type EntreDadosOptions,
  type EntreDadosResolution,
  type EntreDadosRoll,
  type Spread,
} from './games/entre-dados/index.ts';
export {
  ESPELHO_BETS,
  ESPELHO_BET_IDS,
  ESPELHO_CONFIG,
  ESPELHO_DEALER,
  ESPELHO_ID,
  ESPELHO_MATH,
  ESPELHO_NAME,
  JACKPOT_BET,
  SEIS_SEIS_FIXED_RTP,
  SEIS_SEIS_RTP,
  SEIS_SEIS_RTP_AT_SEED,
  compareHands,
  createEspelho,
  createEspelhoJackpot,
  createEspelhoShoe,
  espelhoMathSummary,
  espelhoOutlook,
  readHand,
  resolveEspelhoBet,
  type EspelhoBetId,
  type EspelhoGame,
  type EspelhoHand,
  type EspelhoOptions,
  type EspelhoOutlook,
  type EspelhoResolution,
  type HandValues,
  type JackpotMeterEvent,
} from './games/espelho/index.ts';
export {
  DISTINCT_ROLLS,
  INFINITE_SHOE,
  TRANCAR_BET,
  TRANCAR_BETS,
  TRANCAR_CONFIG,
  TRANCAR_DEALER,
  TRANCAR_DECISIONS,
  TRANCAR_ID,
  TRANCAR_MATH,
  TRANCAR_NAME,
  TRANCAR_SIX_DECK,
  TRANCAR_WITHOUT_FREE,
  WITHOUT_FREE_ONE_ONE,
  beatChance,
  bestChoice,
  createTrancar,
  createTrancarShoe,
  feeRate,
  isFreeReroll,
  lockChoice,
  lockedDie,
  otherDie,
  paidRerollFee,
  referenceStrategy,
  rerollFee,
  rerollValue,
  rollLabel,
  rollValues,
  shoeTotals,
  standValue,
  strategyMath,
  trancarMathSummary,
  trancarOptions,
  trancarStrategy,
  trancarWins,
  withDie,
  type DealerTotals,
  type DieIndex,
  type DieRerolledEvent,
  type DistinctRoll,
  type RollStrategy,
  type RollValues,
  type StrategyMath,
  type TrancarBetId,
  type TrancarChoice,
  type TrancarData,
  type TrancarGame,
  type TrancarOptions,
  type TrancarRules,
  type TrancarState,
} from './games/trancar/index.ts';
export {
  roundsForTolerance,
  simulate,
  type BetStatistics,
  type SimulationOptions,
  type SimulationReport,
} from './math/simulate.ts';
export {
  ProgressiveJackpot,
  type ExactAmount,
  type ProgressiveOptions,
  type ProgressiveSnapshot,
  type ProgressiveState,
} from './progressive/progressive.ts';
export { createCryptoRng, type RandomValuesSource } from './rng/crypto.ts';
export { randomInt, shuffleInPlace, type IntegerRng, type Rng } from './rng/rng.ts';
export { createSeededRng, type Seed } from './rng/seeded.ts';
